# Generated by Django 3.0.5 on 2020-04-29 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Book Title')),
                ('book_image', models.ImageField(default='book.jpg', upload_to='books/cover/', verbose_name='Book Cover Image')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, verbose_name='Publish Date')),
                ('book_or_Novel', models.CharField(choices=[('Book', 'Book'), ('Novel', 'Novel')], default='Book', max_length=5, verbose_name='Type')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.Author', verbose_name='The Author')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(auto_created='fr', default='fr', max_length=2)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Book Title')),
                ('book_Bio', models.TextField(blank=True, null=True, verbose_name='Book Bio')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='Orginal Book')),
            ],
            options={
                'verbose_name': 'French Translation',
                'verbose_name_plural': 'French Translation',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(auto_created='en', default='en', max_length=2)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Book Title')),
                ('book_Bio', models.TextField(blank=True, null=True, verbose_name='Book Bio')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='Orginal Book')),
            ],
            options={
                'verbose_name': 'English Translation',
                'verbose_name_plural': 'English Translation',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='genres', to='books.Genres', verbose_name='Genres'),
        ),
        migrations.CreateModel(
            name='AR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(auto_created='ar', default='ar', max_length=2)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Book Title')),
                ('book_Bio', models.TextField(blank=True, null=True, verbose_name='Book Bio')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='Orginal Book')),
            ],
            options={
                'verbose_name': 'Arabic Translation',
                'verbose_name_plural': 'Arabic Translation',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('book', 'user')},
            },
        ),
    ]
