# Generated by Django 3.0.4 on 2020-04-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[(1, 'Novel'), (2, 'Drama'), (3, 'Fantasy'), (4, 'Fiction'), (5, 'Advanture')], default='1', max_length=100),
        ),
    ]
