# Generated by Django 3.0.4 on 2020-04-03 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200403_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='born_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='author',
            name='profile',
            field=models.TextField(default='SOME STRING', max_length=2000),
        ),
        migrations.AddField(
            model_name='author',
            name='type',
            field=models.CharField(default='روائي', max_length=255),
        ),
    ]
