# Generated by Django 3.0.4 on 2020-04-03 08:08

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200403_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='author',
            name='type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Novel'), (2, 'Drama'), (3, 'Fantasy'), (4, 'Fiction'), (5, 'Advanture')], max_length=9),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
