# Generated by Django 3.0.4 on 2020-04-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200403_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_Bio',
            field=models.TextField(default=''),
        ),
    ]
