# Generated by Django 3.0.4 on 2020-04-03 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_book_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='profile',
            new_name='author_Bio',
        ),
    ]
