# Generated by Django 3.0.4 on 2020-04-03 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200403_0811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='author_Name',
        ),
    ]
