# Generated by Django 3.0.4 on 2020-04-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20200403_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[(1, 'Book'), (2, 'Novel')], default=1, max_length=1),
        ),
    ]
