# Generated by Django 3.0.4 on 2020-04-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20200403_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('BooK', '1'), ('Novel', '2')], default='1', max_length=5),
        ),
    ]
