# Generated by Django 3.0.4 on 2020-04-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20200403_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='type',
        ),
        migrations.AddField(
            model_name='book',
            name='book_or_Novel',
            field=models.CharField(choices=[('BooK', 'book'), ('Novel', 'Novel')], default='1', max_length=5),
        ),
    ]
