# Generated by Django 3.0.4 on 2020-04-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20200403_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='auther',
            new_name='author',
        ),
    ]
