# Generated by Django 3.0.4 on 2020-04-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20200405_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book',
            new_name='genres',
        ),
    ]
