# Generated by Django 3.0.4 on 2020-04-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20200405_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='book.jpg', upload_to='books/cover/'),
        ),
    ]
