# Generated by Django 3.0.4 on 2020-04-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_book_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='Author_Image',
            field=models.ImageField(default='author.jpg', upload_to='books/author/'),
        ),
    ]
