# Generated by Django 3.0.4 on 2020-04-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_author_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_Bio',
            field=models.TextField(default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='type',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_or_Novel',
            field=models.CharField(choices=[('Book', 'Book'), ('Novel', 'Novel')], default='1', max_length=5),
        ),
    ]
