# Generated by Django 3.0.4 on 2020-04-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20200413_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='type',
            new_name='short',
        ),
    ]
