# Generated by Django 3.0.5 on 2020-04-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_auto_20200413_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_or_Novel',
            field=models.CharField(choices=[('Book', 'Book'), ('Novel', 'Novel')], default='Book', max_length=5),
        ),
    ]
