# Generated by Django 3.0.5 on 2020-04-28 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_auto_20200427_1931'),
        ('books', '0025_auto_20200425_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.Author'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
