# Generated by Django 3.0.5 on 2020-04-28 04:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_auto_20200427_1931'),
        ('books', '0026_auto_20200428_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_Bio',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.Author', verbose_name='The Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='book.jpg', upload_to='books/cover/', verbose_name='Book Cover Image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_or_Novel',
            field=models.CharField(choices=[('Book', 'Book'), ('Novel', 'Novel')], default='Book', max_length=5, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='genres', to='books.Genres', verbose_name='Genres'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Publish Date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Book Title'),
        ),
        migrations.CreateModel(
            name='AR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(auto_created='ar', default='ar', max_length=2)),
                ('book_Bio', models.TextField(blank=True, null=True, verbose_name='Book Bio')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Book Title')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='Orginal Book')),
            ],
            options={
                'verbose_name': 'Arabic Translation',
                'verbose_name_plural': 'Arabic Translation',
            },
        ),
    ]
