# Generated by Django 3.0.5 on 2020-04-28 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_auto_20200428_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='EN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(auto_created='en', default='en', max_length=2)),
                ('book_Bio', models.TextField(blank=True, null=True, verbose_name='Book Bio')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Book Title')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='Orginal Book')),
            ],
            options={
                'verbose_name': 'English Translation',
                'verbose_name_plural': 'English Translation',
            },
        ),
    ]
