# Generated by Django 3.0.6 on 2020-05-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='love',
            options={'verbose_name': 'حب', 'verbose_name_plural': 'المحبين'},
        ),
    ]
