# Generated by Django 3.2 on 2023-10-04 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authors', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الكتاب')),
                ('book_image', models.ImageField(default='book.jpg', upload_to='books/cover/', verbose_name='صورة الغلاف')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ النشر')),
                ('book_or_Novel', models.CharField(choices=[('Book', 'كتاب'), ('Novel', 'رواية')], default='Book', max_length=5, verbose_name='نوع الكتاب')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author', verbose_name='المؤلف')),
                ('genres', models.ManyToManyField(blank=True, related_name='genres', to='books.Genres', verbose_name='التصنيفات')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('book', 'user')},
            },
        ),
    ]
