# Generated by Django 3.0.4 on 2020-04-04 07:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20200403_1453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bloga',
            new_name='blogs',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='contet',
            new_name='content',
        ),
    ]
