# Generated by Django 4.2.6 on 2023-10-05 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Writer name')),
                ('short', models.CharField(blank=True, max_length=255, null=True, verbose_name='Short text about writer')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Writer Full Bio')),
                ('image', models.ImageField(default='author.jpg', upload_to='author/images', verbose_name='Writer Profile Image')),
                ('born_date', models.DateField(default=django.utils.timezone.now, verbose_name='Writwe Birth Date')),
            ],
        ),
    ]
