# Generated by Django 3.0.4 on 2020-04-08 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='<django.db.models.fields.related.OneToOneField>',
        ),
    ]
