# Generated by Django 3.0.4 on 2020-04-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200408_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='<django.db.models.fields.related.OneToOneField>',
            field=models.ImageField(upload_to='static/user/<django.db.models.fields.related.OneToOneField>/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_Bio',
            field=models.TextField(max_length=313, verbose_name='Bio'),
        ),
    ]
