# Generated by Django 3.0.4 on 2020-04-08 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200408_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='<django.db.models.fields.related.OneToOneField>',
        ),
    ]
