# Generated by Django 3.0.4 on 2020-04-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200408_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='<django.db.models.fields.related.OneToOneField>',
            new_name='image',
        ),
    ]
