# Generated by Django 3.0.4 on 2020-04-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200408_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/user/<django.db.models.fields.related.OneToOneField>/', verbose_name='Profile Picture'),
        ),
    ]
