# Generated by Django 3.0.4 on 2020-04-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200408_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='001',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/<django.db.models.fields.related.OneToOneField>/', verbose_name='Profile Picture'),
        ),
    ]
