# Generated by Django 3.0.4 on 2020-04-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200408_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='001',
            field=models.ImageField(blank=True, null=True, upload_to='pictuers/users/profiles', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_Bio',
            field=models.TextField(blank=True, max_length=313, verbose_name='Bio'),
        ),
    ]
