# Generated by Django 3.0.4 on 2020-04-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200408_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='001',
            field=models.ImageField(default='default.png', upload_to='pictuers/users/profiles', verbose_name='Profile Picture'),
        ),
    ]
