# Generated by Django 3.0.4 on 2020-04-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200408_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='001',
            field=models.ImageField(default='default.png', upload_to='pictuers/users/profiles'),
        ),
    ]
