# Generated by Django 3.0.4 on 2020-04-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200408_1113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
