# Generated by Django 3.0.4 on 2020-04-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
