# Generated by Django 3.0.4 on 2020-04-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='users/Profiles/'),
        ),
    ]
