# Generated by Django 3.0.4 on 2020-04-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20200410_0746'),
        ('users', '0019_auto_20200410_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='save', to='posts.Post'),
        ),
    ]
