# Generated by Django 3.0.4 on 2020-04-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_author_author_image'),
        ('users', '0020_profile_saves'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.Book'),
        ),
    ]
