# Generated by Django 3.0.4 on 2020-04-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20200413_0737'),
        ('users', '0021_profile_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loves',
            field=models.ManyToManyField(blank=True, related_name='loves', to='posts.UserPost'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='save', to='posts.UserPost'),
        ),
    ]
