# Generated by Django 3.0.4 on 2020-04-13 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20200413_0737'),
        ('users', '0023_remove_profile_loves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='saves',
        ),
        migrations.AddField(
            model_name='profile',
            name='saves',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='save', to='posts.UserPost'),
        ),
    ]
