# Generated by Django 3.0.4 on 2020-04-13 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_author_author_image'),
        ('posts', '0020_auto_20200413_0737'),
        ('users', '0024_auto_20200413_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='books.Book'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='saves',
        ),
        migrations.AddField(
            model_name='profile',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='save', to='posts.UserPost'),
        ),
    ]
