# Generated by Django 3.0.4 on 2020-04-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_remove_post_loves'),
        ('users', '0025_auto_20200413_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loves',
            field=models.ManyToManyField(blank=True, related_name='loves', to='posts.UserPost'),
        ),
    ]
