# Generated by Django 3.0.4 on 2020-04-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_remove_post_title'),
        ('users', '0027_remove_profile_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='loves',
            field=models.ManyToManyField(blank=True, related_name='loves', to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='save', to='posts.Post'),
        ),
    ]
