# Generated by Django 3.0.5 on 2020-04-27 05:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('Author_Image', models.ImageField(default='author.jpg', upload_to='author/images')),
                ('born_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(auto_created='ar', default='ar', max_length=2)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المؤلف')),
                ('short', models.CharField(blank=True, max_length=255, null=True, verbose_name='مختصر')),
                ('author_Bio', models.TextField(blank=True, null=True, verbose_name='معلومات الكاتب')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authors.Author', verbose_name='ملف المؤلف')),
            ],
            options={
                'verbose_name': 'Authors(Arabic)',
                'verbose_name_plural': 'Authors(Arabic)',
            },
        ),
    ]
