# Generated by Django 3.2 on 2023-10-04 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('Author_Image', models.ImageField(default='author.jpg', upload_to='author/images', verbose_name='صورة المؤلف')),
                ('born_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الولادة')),
            ],
        ),
    ]
