# Generated by Django 3.0.5 on 2020-04-27 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(auto_created='en', default='en', max_length=2)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Author Name')),
                ('short', models.CharField(blank=True, max_length=255, null=True, verbose_name='Short')),
                ('author_Bio', models.TextField(blank=True, null=True, verbose_name='Author Bio')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authors.Author', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Authors(Arabic)',
                'verbose_name_plural': 'Authors(Arabic)',
            },
        ),
        migrations.DeleteModel(
            name='AR',
        ),
    ]
