# Generated by Django 3.0.5 on 2020-04-27 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20200427_0531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='en',
            options={'verbose_name': 'English Translation)', 'verbose_name_plural': 'English Translation'},
        ),
        migrations.CreateModel(
            name='AR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(auto_created='ar', default='ar', max_length=2)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المؤلف')),
                ('short', models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف قصير')),
                ('author_Bio', models.TextField(blank=True, null=True, verbose_name='معلومات الكاتب او المؤلف')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authors.Author', verbose_name='المؤلف')),
            ],
            options={
                'verbose_name': 'الترجمة العربية)',
                'verbose_name_plural': 'الترجمة العربية',
            },
        ),
    ]
