# Generated by Django 3.0.5 on 2020-04-27 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_auto_20200427_0632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ar',
            options={'verbose_name': 'Arabic Translateion)', 'verbose_name_plural': 'Arabic Translateion'},
        ),
        migrations.AlterField(
            model_name='ar',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authors.Author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='ar',
            name='author_Bio',
            field=models.TextField(blank=True, null=True, verbose_name='Author Bio'),
        ),
        migrations.AlterField(
            model_name='ar',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Author Name'),
        ),
        migrations.AlterField(
            model_name='ar',
            name='short',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Short'),
        ),
        migrations.CreateModel(
            name='FR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(auto_created='fr', default='fr', max_length=2)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Author Name')),
                ('short', models.CharField(blank=True, max_length=255, null=True, verbose_name='Short')),
                ('author_Bio', models.TextField(blank=True, null=True, verbose_name='Author Bio')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authors.Author', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'French Translateion)',
                'verbose_name_plural': 'French Translateion',
            },
        ),
    ]
