# Generated by Django 3.2 on 2023-10-04 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(default='en', max_length=2, verbose_name='لغة المستخدم')),
                ('title', models.CharField(default='', max_length=120, verbose_name='العنوان')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ النشر')),
                ('content', models.TextField(default='', verbose_name='محتوى المشاركة')),
                ('archived', models.BooleanField(default=False)),
                ('post_type', models.CharField(choices=[('Q', 'اقتباس'), ('R', 'مراجعة'), ('P', 'منشور')], default='Psot', max_length=1, verbose_name='العنوان')),
                ('for_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book', verbose_name='للكتاب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
    ]
