# Generated by Django 3.2 on 2023-10-04 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user', verbose_name='المستخدم')),
                ('picture', models.ImageField(blank=True, default='user.png', null=True, upload_to='users/Profiles/', verbose_name='الصورة الشخصية')),
                ('bio', models.CharField(blank=True, max_length=221, null=True, verbose_name='السيرة الذاتية')),
                ('lang', models.CharField(choices=[('en', 'English'), ('ar', 'العربية'), ('fr', 'français')], default='en', max_length=2, verbose_name='لغة المستخدم')),
                ('pass_recover_token', models.CharField(blank=True, max_length=10, null=True, verbose_name='رمز التحقق')),
                ('books', models.ManyToManyField(blank=True, related_name='books', to='books.Book', verbose_name='الكتب التي تم قراءتها')),
            ],
        ),
    ]
