# Generated by Django 3.0.4 on 2020-04-03 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0012_auto_20200403_0947'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_edit_date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(default='')),
                ('post_type', models.CharField(choices=[('Q', 'Quote'), ('R', 'Reviw'), ('P', 'Post')], default='Psot', max_length=1)),
                ('for_book', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
