# Generated by Django 3.0.4 on 2020-04-09 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0012_auto_20200409_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='loved',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='like',
        ),
    ]
