# Generated by Django 3.0.4 on 2020-04-09 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0013_auto_20200409_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='loved',
            field=models.ManyToManyField(related_name='loves', to=settings.AUTH_USER_MODEL),
        ),
    ]
