# Generated by Django 3.0.4 on 2020-04-09 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20200409_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='loved',
            new_name='loves',
        ),
    ]
