# Generated by Django 3.0.4 on 2020-04-13 07:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_author_author_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0017_sharing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sharing',
            new_name='Postin',
        ),
    ]
