# Generated by Django 3.0.4 on 2020-04-13 07:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_author_author_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0018_auto_20200413_0733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postin',
            new_name='UserPost',
        ),
    ]
