# Generated by Django 3.0.4 on 2020-04-13 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0019_auto_20200413_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='loves',
            field=models.ManyToManyField(blank=True, related_name='ToDele', to=settings.AUTH_USER_MODEL),
        ),
    ]
