# Generated by Django 3.0.4 on 2020-04-13 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20200413_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='loves',
        ),
    ]
