# Generated by Django 3.0.4 on 2020-04-13 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_remove_post_loves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
