# Generated by Django 3.0.2 on 2020-04-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='archived',
            field=models.BooleanField(default=True),
        ),
    ]
