# Generated by Django 3.0.2 on 2020-04-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_post_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='archived',
        ),
    ]
